### ISSUE TITLE
License for Tableau Hyper API is very hard to find

### ISSUE THREAD

**Issue by WilliamRoyNelson** [tableau/hyper-db#102]
I might be missing something obvious on the documentation page, but the license doesn't seem to appear anywhere.
For the C++ and Java distributions, I can download the source, unzip the .zip file and find the license inside.
For Python, on the other hand, there's only a .whl file. I luckily know that .whl is a .zip in disguise, and can find the license in the .dist-info folder inside.

This seems like a LOT of extra work to find the license, and since this product is presumably meant for business purposes, it's really important that potential users be able to easily find the license so that they can get approval from someone authorized to agree to the license.

Can the license be added to the documentation page in an easily found location?

Also, since it can't hurt to ask, could the license be changed to MIT like many of the other Tableau projects? That'd make it extremely easy to approve for use in a corporate environment.

**Comment by vogelsgesang** [comment]
Thanks for bringing this up!

We are currently in the progress of rectifying the situtation. We are not 100% through the processes, yet, but things are looking good so far 🙂

**Comment by vogelsgesang** [comment]
And we are done 🙂 The next release of Hyper API will be licensed under the Apache 2.0 license

**Comment by djouallah** [comment]
is the source under Apache 2 license or just the binary ?

**Comment by vogelsgesang** [comment]
The published artifacts (precompiled hyperd binary and the corresponding Python files, C++ headers, etc.) are Apache-2 licensed. The source code for Hyper itself is not open-source

**Comment by WilliamRoyNelson** [comment]
Thank you! Hopefully a few of my coworkers are able to do some interesting things with this library! I'm excited to see what they come up with.
