### ISSUE TITLE
Hyperapi download linux dependencies

### ISSUE THREAD

**Issue by kishore-perumal** [tableau/hyper-db#13]
Hi,

I see that when I try to download lib files for python linux version, it throws Not found. Here is the url it navigates,

https://downloads.tableau.com/tssoftware//tableauhyperapi-0.0.17002-none-manylinux2014_x86_64.whl.

Can you please send me the linux based python. wheel file

**Comment by vogelsgesang** [comment]
Thanks for reporting! The correct path is

https://downloads.tableau.com/tssoftware/tableauhyperapi-0.0.17002-py3-none-manylinux2014_x86_64.whl

I will fix that in our website in a minute.

By the way: You can also install Hyper API using

```
pip install tableauhyperapi
```

without first downloading the wheel manually

**Comment by kishore-perumal** [comment]
Thanks for support
